const experienceLevelMap = { 'SE': 0, 'MI': 1, 'EN': 2, 'EX': 3 };
const employmentTypeMap = { 'FT': 0, 'CT': 1, 'FL': 3, 'PT': 4, };
const companyLocationMap = {
    'US': 0,
    'CA': 1,
    'DE': 2,
    'GB': 3,
    'IN': 4,
    'HK': 5,
    'NG': 6,
    'ES': 7,
    'PT': 8,
    'GR': 9,
    'NL': 10,
    'CH': 11,
    'CF': 12,
    'FR': 13,
    'FI': 14,
    'UA': 15,
    'IE': 16,
    'IL': 17,
    'GH': 18,
    'CO': 19,
    'SG': 20,
    'AU': 21,
    'SE': 22,
    'SI': 23,
    'MX': 24,
    'TH': 25,
    'HR': 26,
    'BR': 27,
    'RU': 28,
    'IT': 29,
    'MA': 30,
    'PL': 31,
    'AL': 32,
    'AR': 33,
    'LT': 34,
    'CR': 35,
    'IR': 36,
    'BS': 37,
    'HU': 38,
    'AT': 39,
    'SK': 40,
    'AM': 41,
    'BA': 42,
    'KE': 43,
    'MK': 44,
    'LV': 45,
    'PK': 46,
    'AS': 47,
    'VN': 48,
    'EE': 49,
    'AM': 50,
    'AM': 51,
    'AM': 52,
    'AM': 53,
    'AM': 54,
    'AM': 55,
    'AM': 56,
    'AM': 57,
    'AM': 58,
    'AM': 59,
    'CZ': 60,
    'TR': 61,
    'PR': 62,
    'DZ': 63,
    'RO': 64,
    'IQ': 65,
    'BE': 66,
    'ID': 67,
    'EG': 68,
    'AE': 69,
    'MY': 70,
    'HN': 71,
    'JP': 72,
    'DK': 73,
    'BO': 74,
    'PH': 75,
    'LU': 76,
    'CN': 77,
    'NZ': 78,
    'CL': 79,
    'MD': 80,
    'MT': 81,
};
const companySizeMap = { 'S': 0, 'M': 1, 'L': 2 };
const jobTitleMap = {
    'Principal Data Scientist': 0,
    'ML Engineer': 1,
    'Data Scientist': 2,
    'Applied Scientist': 3,
    'Data Analyst': 4,
    'Data Modeler': 5,
    'Research Engineer': 6,
    'Analytics Engineer': 7,
    'Business Intelligence Engineer': 8,
    'Machine Learning Engineer': 9,
    'Data Strategist': 10,
    'Data Engineer': 11,
    'Computer Vision Engineer': 12,
    'Data Architect': 13,
    'Applied Machine Learning Engineer': 14,
    'AI Developer': 15,
    'Data Quality Analyst': 16,
    'Compliance Data Analyst': 17,
    'Data Science Engineer': 18,
    'Lead Data Scientist': 19,
    'BI Analyst': 20,
    'Lead Machine Learning Engineer': 21,
    'NLP Engineer': 22,
    'Research Scientist': 23,
    'BI Data Analyst': 24,
    'Data Analytics Engineer': 25,
    'ETL Developer': 26,
    'AI Scientist': 27,
    'Data Scientist Lead': 28,
    'Data Science Manager': 29,
    'Data Specialist': 30,
    'Data Operations Engineer': 31,
    'Business Data Analyst': 32,
    'Applied Machine Learning Scientist': 33,
    'Machine Learning Research Engineer': 34,
    'Cloud Data Architect': 35,
    'Data Operations Analyst': 36,
    'Computer Vision Software Engineer': 37,
    'Data Analytics Consultant': 38,
    'Product Data Analyst': 39,
    'Machine Learning Infrastructure Engineer': 40,
    'Financial Data Analyst': 41,
    'Data Operations Manager': 42,
    'Director of Data Science': 43,
    'Data Science Consultant': 44,
    '3D Computer Vision Researcher': 45,
    'Staff Data Scientist': 46,
    'Big Data Architect': 47,
    'Lead Data Analyst': 48,
    'Marketing Data Analyst': 49,
    'Cloud Data Engineer': 50,
    'Finance Data Analyst': 51,
    'Data Analytics Manager': 52,
    'Applied Data Scientist': 53,
    'Staff Data Analyst': 54,
    'ETL Engineer': 55,
    'Data DevOps Engineer': 56,
    'Head of Data': 57,
    'Data Manager': 58,
    'Machine Learning Researcher': 59,
    'MLOps Engineer': 60,
    'Autonomous Vehicle Technician': 61,
    'Cloud Database Engineer': 62,
    'Software Data Engineer': 63,
    'AI Programmer': 64,
    'BI Developer': 65,
    'Data Science Lead': 66,
    'Deep Learning Researcher': 67,
    'Data Analytics Specialist': 68,
    'Insight Analyst': 69,
    'Deep Learning Engineer': 70,
    'Data Management Specialist': 71,
    'Power BI Developer': 72,
    'Product Data Scientist': 73,
    'Marketing Data Engineer': 74,
    'Azure Data Engineer': 75,
    'Manager Data Management': 76,
    'Machine Learning Manager': 77,
    'Big Data Engineer': 78,
    'BI Data Engineer': 79,
    'Machine Learning Scientist': 80,
    'Data Infrastructure Engineer': 81,
    'Machine Learning Software Engineer': 82,
    'Head of Data Science': 83,
    'Data Analytics Lead': 84,
    'Data Lead': 85,
    'Machine Learning Developer': 86,
    'Principal Machine Learning Engineer': 87,
    'Principal Data Architect': 88,
    'Principal Data Analyst': 89,
    'Data Science Tech Lead': 90,
    'Lead Data Engineer': 91,
    'Head of Machine Learning': 92,
    'Principal Data Engineer': 93
};
module.exports = { experienceLevelMap, employmentTypeMap, companyLocationMap, companySizeMap, jobTitleMap };
