### register to buzzmake
POST http://localhost:3000/api/auth/register
Content-Type: application/json
 
{
    "email": "aa@gmail.com",
    "password": "test123455",
    "name": "hanwna tossy"
}
### login to account
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "josepht@gmail.com",
    "password": "test123455"
}
### refresh a token
POST http://localhost:3000/api/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTUzNTYwMzQsImV4cCI6MTc0NjkxMzYzNCwiYXVkIjoiNjYzZTQxM2YzMWNhM2Q5NDE4MGIwZWU5IiwiaXNzIjoiam9zZXBoLmNvbSJ9.HtN4WOGrmdi3oWE2haOf3Lzg7A5alh11mAAOdSE1lLw"
}
### logout of account and remove tokens
DELETE http://localhost:3000/api/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTUzNTYwNjgsImV4cCI6MTc0NjkxMzY2OCwiYXVkIjoiNjYzZTQxM2YzMWNhM2Q5NDE4MGIwZWU5IiwiaXNzIjoiam9zZXBoLmNvbSJ9.ALO8mbrL_t9EdoJTJNPKBlmexYe9JbGxDoQdlGe1C1s"
}

### get all users
GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTUzNTYwOTQsImV4cCI6MTcxNTM1OTY5NCwiYXVkIjoiNjYzZTQxM2YzMWNhM2Q5NDE4MGIwZWU5IiwiaXNzIjoiam9zZXBoLmNvbSJ9.KufBicSIvggDQ8IC_f4fd_rwO11QOJicpfCDOcwO7K4
### get a user data 
GET http://localhost:3000/api/users/662d0e2aed64ba62bbe44db8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTUxNzUzMTgsImV4cCI6MTcxNTE3ODkxOCwiYXVkIjoiNjYzYjdmODQ4MjA1ZGE0ZjkxN2M4YWU4IiwiaXNzIjoiam9zZXBoLmNvbSJ9.GDRb2GBSfraoLCiYAdsEp2dpP0r9iWrxM-XTo_bWD44
### get buzzes for a certain user
GET http://localhost:3000/api/users/buzzes/662d0e2aed64ba62bbe44db8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTUxNzUzMTgsImV4cCI6MTcxNTE3ODkxOCwiYXVkIjoiNjYzYjdmODQ4MjA1ZGE0ZjkxN2M4YWU4IiwiaXNzIjoiam9zZXBoLmNvbSJ9.GDRb2GBSfraoLCiYAdsEp2dpP0r9iWrxM-XTo_bWD44

### get all buzzes
GET http://localhost:3000/api/buzzes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTUzNjAyMDEsImV4cCI6MTcxNTQwMzQwMSwiYXVkIjoiNjYzZTUxMGQzMTM2NTUyNjk4MWZiMGIxIiwiaXNzIjoiam9zZXBoLmNvbSJ9.s-5SW8TLTs3blQRB2C50Lkpk734Lb17otZ-0MtR8GCQ
### get buzzes of type ( buzz type ex: Educational, It, etc ... )
GET http://localhost:3000/api/buzzes/buzz-type/663e4af4a90e57066dd34310
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTUzNjAyMDEsImV4cCI6MTcxNTQwMzQwMSwiYXVkIjoiNjYzZTUxMGQzMTM2NTUyNjk4MWZiMGIxIiwiaXNzIjoiam9zZXBoLmNvbSJ9.s-5SW8TLTs3blQRB2C50Lkpk734Lb17otZ-0MtR8GCQ
### get a certain buzz 
GET http://localhost:3000/api/buzzes/663e523c5fd2e621caaf269f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTUzNjAyMDEsImV4cCI6MTcxNTQwMzQwMSwiYXVkIjoiNjYzZTUxMGQzMTM2NTUyNjk4MWZiMGIxIiwiaXNzIjoiam9zZXBoLmNvbSJ9.s-5SW8TLTs3blQRB2C50Lkpk734Lb17otZ-0MtR8GCQ
### add new buzz
POST http://localhost:3000/api/buzzes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTUzNjAyMDEsImV4cCI6MTcxNTQwMzQwMSwiYXVkIjoiNjYzZTUxMGQzMTM2NTUyNjk4MWZiMGIxIiwiaXNzIjoiam9zZXBoLmNvbSJ9.s-5SW8TLTs3blQRB2C50Lkpk734Lb17otZ-0MtR8GCQ

{
    "name": "buzz",
    "url": "www.google.com",
    "private": false,
    "description": "test",
    "buzzType": "663e4af4a90e57066dd34310"
}
### edit a buzz
PUT http://localhost:3000/api/buzzes/662c0cf2d137b3764202e3a8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTQxNjIzNTAsImV4cCI6MTcxNDE2NTk1MCwiYXVkIjoiNjYyYzBhNWQ5Yzg2NTQyMzVmNzEyNTAwIiwiaXNzIjoiam9zZXBoLmNvbSJ9.7zjIQjUfmWAKzuQrt6Iz6DB_XuKRCDKpKmdaPFT3cik

{
    "name": "It's not a ticket"
}
### delete buzz
DELETE http://localhost:3000/api/buzzes/662c0cf2d137b3764202e3a8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTQxNjIzNTAsImV4cCI6MTcxNDE2NTk1MCwiYXVkIjoiNjYyYzBhNWQ5Yzg2NTQyMzVmNzEyNTAwIiwiaXNzIjoiam9zZXBoLmNvbSJ9.7zjIQjUfmWAKzuQrt6Iz6DB_XuKRCDKpKmdaPFT3cik

### get buzz types
GET http://localhost:3000/api/buzz-types
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTUzNjAyMDEsImV4cCI6MTcxNTQwMzQwMSwiYXVkIjoiNjYzZTUxMGQzMTM2NTUyNjk4MWZiMGIxIiwiaXNzIjoiam9zZXBoLmNvbSJ9.s-5SW8TLTs3blQRB2C50Lkpk734Lb17otZ-0MtR8GCQ
### create buzz type
POST http://localhost:3000/api/buzz-types
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTUzNjAyMDEsImV4cCI6MTcxNTQwMzQwMSwiYXVkIjoiNjYzZTUxMGQzMTM2NTUyNjk4MWZiMGIxIiwiaXNzIjoiam9zZXBoLmNvbSJ9.s-5SW8TLTs3blQRB2C50Lkpk734Lb17otZ-0MtR8GCQ

{
    "name": "Social Media"
}
### delete buzz type
DELETE http://localhost:3000/api/buzz-types/663e4ad8a90e57066dd34308
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTUzNjAyMDEsImV4cCI6MTcxNTQwMzQwMSwiYXVkIjoiNjYzZTUxMGQzMTM2NTUyNjk4MWZiMGIxIiwiaXNzIjoiam9zZXBoLmNvbSJ9.s-5SW8TLTs3blQRB2C50Lkpk734Lb17otZ-0MtR8GCQ
### create offer to a certain buzz
POST http://localhost:3000/api/offer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTUzNjUyMzEsImV4cCI6MTcxNTQwODQzMSwiYXVkIjoiNjYzZTY1NmUxZGNhM2U2OTYwOWFhZjhkIiwiaXNzIjoiam9zZXBoLmNvbSJ9.XfgYTyWaTI0bF_uSUaawuKs7S6-sPu1LK83crctgUI4

{
    "buzzId": "663e62bed1f1eecd9f33d2ac",
    "price": 10
}
